# Generated by Django 5.2.11 on 2026-02-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('REGISTRO_PONTO', 'Registro de Ponto'), ('AJUSTE_PONTO', 'Ajuste de Ponto'), ('FECHAMENTO_SEMANA', 'Fechamento Semanal'), ('REABERTURA_SEMANA', 'Reabertura Semanal'), ('APROVACAO_AJUSTE', 'Aprovação de Ajuste'), ('REJEICAO_AJUSTE', 'Rejeição de Ajuste')], max_length=20, verbose_name='Tipo de Ação')),
                ('descricao', models.TextField(help_text='Descrição detalhada da ação realizada', verbose_name='Descrição')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('dados_antes', models.JSONField(blank=True, help_text='Estado do objeto antes da alteração (JSON)', null=True, verbose_name='Dados Antes')),
                ('dados_depois', models.JSONField(blank=True, help_text='Estado do objeto depois da alteração (JSON)', null=True, verbose_name='Dados Depois')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'auditoria_logauditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='auditoria_l_empresa_c04403_idx'), models.Index(fields=['usuario', 'criado_em'], name='auditoria_l_usuario_ae84c6_idx'), models.Index(fields=['tipo_acao'], name='auditoria_l_tipo_ac_142e16_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_l_content_9b61b2_idx')],
            },
        ),
    ]
