# Generated by Django 5.2.11 on 2026-02-17 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3, verbose_name='Tipo')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('origem', models.CharField(choices=[('SISTEMA', 'Sistema'), ('MANUAL', 'Manual'), ('AJUSTE', 'Ajuste'), ('IMPORTACAO', 'Importação')], default='SISTEMA', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
