# Generated by Django 5.2.11 on 2026-02-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_criados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='substitui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituido_por', to='jornada.registroponto', verbose_name='Substitui registro'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ponto', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['empresa', 'usuario', 'data_hora'], name='jornada_reg_empresa_61d2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['empresa', 'usuario', 'tipo', 'status'], name='jornada_reg_empresa_1e1217_idx'),
        ),
    ]
