# Generated by Django 5.2.11 on 2026-02-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('jornada', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Ex: Rede Matriz, WiFi Filial SP', max_length=100, verbose_name='Nome')),
                ('ip', models.GenericIPAddressField(help_text='IP fixo da rede local', verbose_name='Endereço IP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'IP Permitido',
                'verbose_name_plural': 'IPs Permitidos',
                'db_table': 'jornada_ippermitido',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Ex: Matriz, Filial SP, Escritório RJ', max_length=100, verbose_name='Nome do Local')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Coordenada de latitude do centro do local', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Coordenada de longitude do centro do local', max_digits=10, verbose_name='Longitude')),
                ('raio_metros', models.PositiveIntegerField(default=100, help_text='Raio de tolerância em metros a partir do ponto central', verbose_name='Raio em Metros')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Local Permitido',
                'verbose_name_plural': 'Locais Permitidos',
                'db_table': 'jornada_localpermitido',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_hora_desejada', models.DateTimeField(help_text='Data e hora correta que deveria ter sido registrada', verbose_name='Data/Hora Desejada')),
                ('justificativa', models.TextField(help_text='Motivo da solicitação de ajuste', verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('observacao_analise', models.TextField(blank=True, default='', verbose_name='Observação da Análise')),
            ],
            options={
                'verbose_name': 'Solicitação de Ajuste',
                'verbose_name_plural': 'Solicitações de Ajuste',
                'db_table': 'jornada_solicitacaoajuste',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RemoveIndex(
            model_name='registroponto',
            name='jornada_reg_empresa_1e1217_idx',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto obrigatória no primeiro registro do dia', null=True, upload_to='fotos_ponto/%Y/%m/%d/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='validacao_local',
            field=models.BooleanField(default=False, help_text='Se o registro passou pela validação de local/IP', verbose_name='Validação de Local'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Sistema Web'), ('MOBILE', 'Aplicativo Mobile'), ('AJUSTE', 'Ajuste Manual')], default='SISTEMA', max_length=10, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='registrado_por',
            field=models.ForeignKey(help_text='Quem realizou o registro (pode ser diferente do usuário em caso de ajuste)', on_delete=django.db.models.deletion.PROTECT, related_name='registros_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUBSTITUIDO', 'Substituído por Ajuste'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='substitui',
            field=models.ForeignKey(blank=True, help_text='Registro que este ajuste substitui', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jornada.registroponto', verbose_name='Substitui Registro'),
        ),
        migrations.AlterModelTable(
            name='registroponto',
            table='jornada_registroponto',
        ),
        migrations.AddField(
            model_name='ippermitido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips_permitidos', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='localpermitido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_permitidos', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='local_utilizado',
            field=models.ForeignKey(blank=True, help_text='Local permitido utilizado para validação', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jornada.localpermitido', verbose_name='Local Utilizado'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['empresa', 'status'], name='jornada_reg_empresa_16403a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['data_hora'], name='jornada_reg_data_ho_e44f54_idx'),
        ),
        migrations.AddField(
            model_name='solicitacaoajuste',
            name='analisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_ajuste', to=settings.AUTH_USER_MODEL, verbose_name='Analisado Por'),
        ),
        migrations.AddField(
            model_name='solicitacaoajuste',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='solicitacaoajuste',
            name='registro_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_ajuste', to='jornada.registroponto', verbose_name='Registro Original'),
        ),
        migrations.AddField(
            model_name='solicitacaoajuste',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_ajuste', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterUniqueTogether(
            name='ippermitido',
            unique_together={('empresa', 'ip')},
        ),
        migrations.AlterUniqueTogether(
            name='localpermitido',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AddIndex(
            model_name='solicitacaoajuste',
            index=models.Index(fields=['empresa', 'status'], name='jornada_sol_empresa_fc6686_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoajuste',
            index=models.Index(fields=['solicitante', 'status'], name='jornada_sol_solicit_c616bc_idx'),
        ),
    ]
