# Generated by Django 5.2.11 on 2026-02-17 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('jornada', '0003_ippermitido_localpermitido_solicitacaoajuste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['-data_hora']},
        ),
        migrations.RemoveIndex(
            model_name='registroponto',
            name='jornada_reg_data_ho_e44f54_idx',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='justificativa_sem_foto',
            field=models.TextField(blank=True, default='', help_text='Motivo informado pelo colaborador ao registrar sem foto', verbose_name='Justificativa para registro sem foto'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ponto', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_ponto/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='local_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ponto', to='jornada.localpermitido'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Sistema Web'), ('MOBILE', 'Aplicativo Mobile'), ('AJUSTE', 'Ajuste Manual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUBSTITUIDO', 'Substituído por Ajuste'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=12),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='substitui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituido_por', to='jornada.registroponto'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ponto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='validacao_local',
            field=models.BooleanField(default=False),
        ),
    ]
