# Generated by Django 5.2.11 on 2026-02-17 18:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoBancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('semana', models.PositiveSmallIntegerField(verbose_name='Semana do Ano')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Horas Trabalhadas')),
                ('horas_esperadas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas Esperadas')),
                ('saldo_semana', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Saldo da Semana')),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Saldo Acumulado')),
                ('fechado', models.BooleanField(default=False, verbose_name='Fechado')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_banco_horas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saldo de Banco de Horas',
                'verbose_name_plural': 'Saldos de Banco de Horas',
                'ordering': ['-ano', '-semana'],
                'indexes': [models.Index(fields=['empresa', 'usuario', 'ano', 'semana'], name='banco_horas_empresa_05a85f_idx'), models.Index(fields=['empresa', 'fechado'], name='banco_horas_empresa_b2aec4_idx')],
                'unique_together': {('empresa', 'usuario', 'ano', 'semana')},
            },
        ),
    ]
