# Generated by Django 5.2.11 on 2026-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('carga_horaria_semanal', models.DecimalField(decimal_places=2, default=44.0, max_digits=4, verbose_name='Carga Horária Semanal (horas)')),
                ('tolerancia_minutos', models.PositiveSmallIntegerField(default=10, help_text='Minutos de tolerância para atrasos e saídas antecipadas.', verbose_name='Tolerância em Minutos')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
